### ISSUE TITLE
Data inputs for univariate time series

### ISSUE THREAD

**Issue by aron-alarik** [IBCNServices/geneticShapelets#18]
Hi, I have a univariate time series with time stamps as a starting point and a target variable array. Not sure how you are processing the data input in the example provided, what are you expecting as Data input into GENDIS. Thanks !!

**Comment by GillesVandewiele** [comment]
Hi,

A `N x M` data matrix and label vector of size `N`, with `N` the number of time series and `M` the time series length.

**Comment by aron-alarik** [comment]
ahaa !! so if I have 2 time series of length 500 each, the input np array becomes (2, 500), and the target label is just 2.
let me try this and get back !! thanks a zillion
