### ISSUE TITLE
Error: No module named 'gendis'

### ISSUE THREAD

**Issue by jadew0321** [IBCNServices/geneticShapelets#20]
The following error is reported when I run the first shell in example.ipynb.
The runing window is shown below. I will appreciate if you can give me some guidance.
![image](https://user-images.githubusercontent.com/67991476/164960353-767e5d11-09b1-4ae2-ab9c-00097324957d.png)
![image](https://user-images.githubusercontent.com/67991476/164960360-3a29ca69-95da-45c7-a902-ec61ff1e7c42.png)
![image](https://user-images.githubusercontent.com/67991476/164960368-0ab23ab9-5c9e-4cfb-9b2d-dab26d26f699.png)

**Comment by GillesVandewiele** [comment]
Did you install it?

**Comment by jadew0321** [comment]
> Did you install. it?

Thanks for your reply. The above problem was solved by restarting my vscode. Thanks for your great contribution again.
