### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by Haoxiang-Sun-BioEng** [IBCNServices/geneticShapelets#24]
Hello Gilles, I am a graduate student currently trying to use GENDIS for a machine learning project. However, when I used command "!pip install gendis", it returns the "ResolutionImpossible" error since GENDIS requires matplotlib version 2.1.2, but now I have matplotlib version 3.5.2. I tried "!pipx install matplotlib==2.1.2" to install the earlier version, and also attempted the clone repository alternative, but both also failed. Any idea on how to get over this problem?

**Comment by GillesVandewiele** [comment]
I don't think GENDIS depends very strongly on that specific version of matplotlib. Could you try installing and ignoring dependencies (on phone atm so cannot give command by heart but there is a flag for that) and see whether that works?

**Comment by Haoxiang-Sun-BioEng** [comment]
Hello Gilles, I just checked that I currently have Python version 3.9.5, while GENDIS supports 3.5.x and 3.6.x, do you think that is why the problem appeared or should it actually be back compatible?
